name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Checkout du code
      - name: Checkout code
        uses: actions/checkout@v2

      # Installer Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '22'

      # Installer les dépendances
      - name: Install dependencies
        run: npm install

      # Exécuter les tests
      - name: Run tests
        run: npm run test:ci

  deploy:
    runs-on: ubuntu-latest
    needs: test
    if: success()

    steps:
      # Checkout du code
      - name: Checkout code
        uses: actions/checkout@v2

      # Déploiement sur Vercel
      - name: Deploy to Vercel
        run: |
          echo "Déploiement sur Vercel"
